from enum import Enum


class Scheme(Enum):
    """Enumeration of storage schemes or protocols."""

    FILE = "file"
    S3 = "s3"
    GITHUB = "github"


class Source(Enum):
    """Enumeration of data processing states."""

    RAW = "raw"
    PROCESSED = "processed"
    TENSOR = "tensor"
    META = "meta"


class ExpirationRule(Enum):
    """Enumeration of futures contract expiration rules."""

    LAST_BUSINESS_DAY_CONTRACT_MONTH = "LAST_BUSINESS_DAY_CONTRACT_MONTH"
    THIRD_LAST_BUSINESS_DAY_CONTRACT_MONTH = "THIRD_LAST_BUSINESS_DAY_CONTRACT_MONTH"
    SEVEN_BUSINESS_DAYS_PRIOR_LAST_BUS_DAY = "SEVEN_BUSINESS_DAYS_PRIOR_LAST_BUS_DAY"
    TENTH_BUSINESS_DAY_CONTRACT_MONTH = "TENTH_BUSINESS_DAY_CONTRACT_MONTH"
    LAST_BUSINESS_DAY_PRIOR_MONTH = "LAST_BUSINESS_DAY_PRIOR_MONTH"
    THIRD_LAST_BUSINESS_DAY_PRIOR_MONTH = "THIRD_LAST_BUSINESS_DAY_PRIOR_MONTH"
    THIRD_FRIDAY_CONTRACT_MONTH = "THIRD_FRIDAY_CONTRACT_MONTH"
    ONE_BUSINESS_DAY_PRIOR_THIRD_WEDNESDAY = "ONE_BUSINESS_DAY_PRIOR_THIRD_WEDNESDAY"
    TWO_BUSINESS_DAYS_PRIOR_THIRD_WEDNESDAY = "TWO_BUSINESS_DAYS_PRIOR_THIRD_WEDNESDAY"
    THREE_BUSINESS_DAYS_BEFORE_25TH_PRIOR_MONTH = (
        "THREE_BUSINESS_DAYS_BEFORE_25TH_PRIOR_MONTH"
    )
    FOUR_BUSINESS_DAYS_BEFORE_25TH_PRIOR_MONTH = (
        "FOUR_BUSINESS_DAYS_BEFORE_25TH_PRIOR_MONTH"
    )
    BUSINESS_DAY_PRIOR_15TH = "BUSINESS_DAY_PRIOR_15TH"
    FEB_LONDON_SPECIAL_RULE = "FEB_LONDON_SPECIAL_RULE"
    LAST_THURSDAY_SPECIAL_RULE = "LAST_THURSDAY_SPECIAL_RULE"
    THURSDAY_PRIOR_SECOND_FRIDAY_CON_MONTH = "THURSDAY_PRIOR_SECOND_FRIDAY_CON_MONTH"
    FIRST_BUSINESS_DAY_AFTER_FIRST_FRIDAY = "FIRST_BUSINESS_DAY_AFTER_FIRST_FRIDAY"


extension_map = {
    Source.RAW: ".zip",
    Source.PROCESSED: ".zip",
    Source.TENSOR: ".pt",
    Source.META: ".yml",
}
